### ISSUE TITLE
Missing metadata

### ISSUE THREAD

**Issue by Androlax2** [Log1x/acf-phone-number#54]
Hello,

There is a problem with the new version of : https://github.com/giggsey/libphonenumber-for-php

Related to this one : https://github.com/giggsey/libphonenumber-for-php/issues/538

We need to change language code in uppercase, otherwise it will throw an exception.

I think you can enforce it in this package to ensure it doesn't throw any exception.

In the README, `->setConfig('default_country', 'us')` should be `->setConfig('default_country', 'US')` 

Maybe I'm wrong, but I have some problems on my website due to that (and Wordpress have in the database `us` for example, so it will throw an exception.

**Comment by Log1x** [comment]
It looks like this has been fixed in https://github.com/giggsey/libphonenumber-for-php/pull/541 but there's no release yet.

Do you think we should still merge in some changes from #55? I think [this](https://github.com/Log1x/acf-phone-number/pull/55/files#diff-55d50d54d8450d5e0a19fbc9d76df5eb2971488b11de6c45131da1fd91cfff12R61) is the only change we'd technically need.

**Comment by Androlax2** [comment]
Hi,

Maybe we can still merge it to ensure it will work whatever ? 
As they didn't release a new version yet, some websites will still have the problem when running `composer update`

It will also ensure the country region code still be uppercase as It should be

**Comment by Log1x** [comment]
Fixed in #55
